### ISSUE TITLE
NameError: name 'AT_BOT' is not defined

### ISSUE THREAD

**Issue by JoinZCoin** [tehranifar/ZTipBot#1]
On launch I get the following in logs.

`Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/local/lib/python3.6/site-packages/discord/client.py", line 251, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 364, in on_message
    if AT_BOT in message.content or (message.channel.is_private and message.author.id != client.user.id):
NameError: name 'AT_BOT' is not defined
2019-05-13 21:40:17,998 [wallet] -INFO- parsing incoming transactions ...
2019-05-13 21:40:17,999 [BitcoinRPC] -DEBUG- --> [{"jsonrpc": "2.0", "method": "listtransactions", "params": ["*", 100, 0], "id": 1}]
2019-05-13 21:41:18,037 [wallet] -INFO- parsing incoming transactions ...
2019-05-13 21:41:18,038 [BitcoinRPC] -DEBUG- --> [{"jsonrpc": "2.0", "method": "listtransactions", "params": ["*", 100, 0], "id": 2}]
2019-05-13 21:42:18,055 [wallet] -INFO- parsing incoming transactions ...
2019-05-13 21:42:18,055 [BitcoinRPC] -DEBUG- --> [{"jsonrpc": "2.0", "method": "listtransactions", "params": ["*", 100, 0], "id": 3}]
2019-05-13 21:43:18,091 [wallet] -INFO- parsing incoming transactions ...
2019-05-13 21:43:18,091 [BitcoinRPC] -DEBUG- --> [{"jsonrpc": "2.0", "method": "listtransactions", "params": ["*", 100, 0], "id": 4}]
`

I have been unable to get the bot to connect with the line 

`AT_BOT = "<@" + os.environ.get('BOT_ID') + ">"
`
It throws error

```
    if AT_BOT in message.content or (message.channel.is_private and message.author.id != client.user.id):
NameError: name 'AT_BOT' is not defined
```

I also had to remove from the last line to 

client.run('TOKEN')

Or the bot will fail to load. 

The bot is showing in the channel but unable to issue commands to the bot.

**Comment by nvdtf** [comment]
Did you define the `BOT_ID` environment variable before starting the bot? I've written a run script to set the necessary parameters.
